version: "3"
services:
    web:
        container_name: nginx
        image: nginx:latest
        environment:
            - DOMAIN=${NGINX_HOST}
        ports:
            - 80:80
        volumes:
            - "./etc/nginx/initialize.conf:/etc/nginx/conf.d/default.conf"
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
    certbot:
        container_name: certbot
        image: certbot/certbot:latest
        depends_on:
            - web
        command: certonly --webroot --webroot-path=/var/www/certbot --agree-tos --staging -d *.${NGINX_HOST} -m ${EMAIL} --no-eff-email
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
